config/routes.rb
Rails.application.routes.draw do
  resources :registrations
  resources :contacts
  resources :patients
  resources :doctors
  resources :books
  resources :authors
  resources :products
  get 'server_sides/ror'

  get 'server_sides/dotnet'

  get 'server_sides/php'

  get 'server_sides/sharepoint'

  get 'free_registrations/students'

  root 'homes#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/appointment.rb
class Appointment < ApplicationRecord
	belongs_to :doctor, foreign_key: "doctor_id"
	belongs_to :patient, foreign_key: "patient_id"
end

app/models/author.rb
class Author < ApplicationRecord
	has_many :books    #@author.books  #Author.first.books
end

app/models/book.rb
class Book < ApplicationRecord
	belongs_to :author, foreign_key: "author_id"  #  @book.author   #  Book.find(1).author.name
end

app/models/contact.rb
class Contact < ApplicationRecord
	#vaidation
	#association
	#callbacks
	after_create :mails

	def mails
		UserMailer.registration_confirmation(self).deliver
		UserMailer.owner(self).deliver
	end

	before_create :name_caps

	def name_caps
		self.name.capitalize!
	end

	before_update :name_all_caps

	def name_all_caps
		self.name.upcase!
	end


end

app/models/doctor.rb
class Doctor < ApplicationRecord
	has_many :appointments
	has_many :patients, :through => "appointments"
end

app/models/patient.rb
class Patient < ApplicationRecord
	has_many :appointments
	has_many :doctors, through: "appointments"
end

app/models/product.rb
class Product < ApplicationRecord
	#validations
	#associations
	#callbacks
	#query
	#class methods
	validates :weight, format: { with: /[0-9]{10}/,
    message: "only allows letters" }
    validates :weight, uniqueness: true
end

app/models/registration.rb
class Registration < ApplicationRecord
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  before_action :set_author, only: [:show, :edit, :update, :destroy]

  # GET /authors
  # GET /authors.json
  def index
    @authors = Author.all
  end

  # GET /authors/1
  # GET /authors/1.json
  def show
  end

  # GET /authors/new
  def new
    @author = Author.new
  end

  # GET /authors/1/edit
  def edit
  end

  # POST /authors
  # POST /authors.json
  def create
    @author = Author.new(author_params)

    respond_to do |format|
      if @author.save
        format.html { redirect_to @author, notice: 'Author was successfully created.' }
        format.json { render :show, status: :created, location: @author }
      else
        format.html { render :new }
        format.json { render json: @author.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /authors/1
  # PATCH/PUT /authors/1.json
  def update
    respond_to do |format|
      if @author.update(author_params)
        format.html { redirect_to @author, notice: 'Author was successfully updated.' }
        format.json { render :show, status: :ok, location: @author }
      else
        format.html { render :edit }
        format.json { render json: @author.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /authors/1
  # DELETE /authors/1.json
  def destroy
    @author.destroy
    respond_to do |format|
      format.html { redirect_to authors_url, notice: 'Author was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_author
      @author = Author.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def author_params
      params.require(:author).permit(:name, :email, :cell)
    end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_book, only: [:show, :edit, :update, :destroy]

  # GET /books
  # GET /books.json
  def index
    @books = Book.all
  end

  # GET /books/1
  # GET /books/1.json
  def show
  end

  # GET /books/new
  def new
    @book = Book.new
  end

  # GET /books/1/edit
  def edit
  end

  # POST /books
  # POST /books.json
  def create
    @book = Book.new(book_params)

    respond_to do |format|
      if @book.save
        format.html { redirect_to @book, notice: 'Book was successfully created.' }
        format.json { render :show, status: :created, location: @book }
      else
        format.html { render :new }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /books/1
  # PATCH/PUT /books/1.json
  def update
    respond_to do |format|
      if @book.update(book_params)
        format.html { redirect_to @book, notice: 'Book was successfully updated.' }
        format.json { render :show, status: :ok, location: @book }
      else
        format.html { render :edit }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /books/1
  # DELETE /books/1.json
  def destroy
    @book.destroy
    respond_to do |format|
      format.html { redirect_to books_url, notice: 'Book was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_book
      @book = Book.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def book_params
      params.require(:book).permit(:author_id, :book_name, :book_price)
    end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/doctors_helper.rb
module DoctorsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/patients_helper.rb
module PatientsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/helpers/server_sides_helper.rb
module ServerSidesHelper
	def self.contact_details
	  address = <<-DOC
	  "S/o M Durga Prasad"		
	  "West Godavari"
	  "Palakollu"
	  "India"
	  "Cell: 1234567895"
	  "Email: srinivaspkl@gmail.com"
	  DOC
	end

	My_time = Time.new.strftime("%d-%m-%Y")
end

app/views/homes/_footer.html.erb
<div id="footer">
	<p>2012. Untitled. All rights reserved. Design by <a href="http://templated.co" rel="nofollow">TEMPLATED</a>. Photos by <a href="http://fotogrph.com/">fotogrph</a>.</p>
</div>
<!-- end #footer -->

app/views/homes/_header.html.erb
		<div id="header">
			<div id="logo">
				<h1><a href="#">Combinations</a></h1>
				<p>Design by <a href="http://templated.co" rel="nofollow">TEMPLATED</a></p>
			</div>
		</div>

app/views/homes/_header1.html.erb
		<div id="header">
			<div id="logo">
				<h1><a href="#">Praveen Blog</a></h1>
				<p>Avinash <a href="http://templated.co" rel="nofollow">praveen</a></p>
			</div>
		</div>

app/views/homes/_menu.html.erb
		<div id="menu-wrapper">
			<ul id="menu">
				<li class="current_page_item"><a href="#"><span>Home</span></a></li>
				<li><a href="/server_sides/ror"><span>ROR</span></a></li>
				<li><%= link_to "PHP", server_sides_php_path %></li>
				<li><span>Links</span>
					<ul>
						<li class="first"> <a href="index">Maecenas luctus lectus</a> </li>
						<li> <a href="search">Integer gravida</a> </li>
						<li class="last"> <a href="about">Ut nonummy rutrum</a> </li>
					</ul>
				</li>
				<li><a href="#"><span>Contact</span></a></li>
			</ul>
			<script type="text/javascript">
			$('#menu').dropotron();
		</script> 
		</div>
		<!-- end #menu -->

app/views/homes/_php.html.erb
<h1>Srinivas is a php students</h1>
<br/>
<input type="text" /><input type="button" />

app/views/homes/_sidebar.html.erb
		<div id="sidebar-bg">
			<div id="sidebar">
				<ul>
					<li>
						<h2>Recent News</h2>
						<ul>
							<li><a href="#">Aliquam libero</a></li>
							<li><a href="#">Consectetuer adipiscing elit</a></li>
							<li><a href="#">Metus aliquam pellentesque</a></li>
							<li><a href="#">Suspendisse iaculis mauris</a></li>
							<li><a href="#">Urnanet non molestie semper</a></li>
							<li><a href="#">Proin gravida orci porttitor</a></li>
						</ul>
					</li>
				</ul>
			</div>
		</div>
		<!-- end #sidebar -->

app/views/homes/_slider.html.erb
		<div id="banner">
			<div id="slider"> <a href="#" class="button previous-button">&lt;</a> <a href="#" class="button next-button">&gt;</a>
				<div class="viewer">
					<div class="reel">
						<div class="slide">
							<h2>This is the first slide.</h2>
							<p>Lorem ipsum dolor sit amet nullam.</p>
							<a class="link" href="#">Full story ...</a><img src="<%= image_path 'img01.jpg' %>" width="900" height="350" alt="" /></div>
						<div class="slide">
							<h2>This is the second slide.</h2>
							<p>Lorem ipsum dolor sit amet nullam.</p>
							<a class="link" href="#">Full story ...</a><%= image_tag 'img01.jpg', size: "900*350" %></div>
					</div>
				</div>
				<div class="indicator">
					<ul>
						<li class="active">1</li>
						<li>2</li>
					</ul>
				</div>
			</div>
			<script type="text/javascript">
				$('#slider').slidertron({
					viewerSelector: '.viewer',
					reelSelector: '.viewer .reel',
					slidesSelector: '.viewer .reel .slide',
					advanceDelay: 3000,
					speed: 'slow',
					navPreviousSelector: '.previous-button',
					navNextSelector: '.next-button',
					indicatorSelector: '.indicator ul li',
					slideLinkSelector: '.link'
				});
			</script> 
		</div>

app/views/homes/index.html.erb
<h1>Homes#index</h1>
<p>Find me in app/views/homes/index.html.erb</p>